Добавлена поддержка базы данных H2
mkudryavtsev90/java-filmorate pull request #3
Opened 2022-10-11 18:00 UTC by mkudryavtsev90

2022-10-11 19:34 UTC, Frilock requested changes
В целом все здорово, пару вопросов написал Вам, при следующей итерации можете на них ответить.

2022-10-11 19:34 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/mapper/FilmRowMapper.java
> +        film.setDuration(Duration.ofMinutes(rs.getInt("film.duration")));
Duration.ofMinutes не вернет ли ошибку, если туда null придет? Реализацию метода смотрели? Или уверены, что 
rs.getInt("film.duration") != null?

2022-10-11 19:34 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/mapper/UserRowMapper.java
> +        user.setBirthday(rs.getDate("birthday").toLocalDate());
rs.getDate("birthday").toLocalDate() Аналогичный вопрос, rs.getDate("birthday") - null не вернет? А то NPE будет

2022-10-11 19:34 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/repository/impl/GenreDBRepository.java
> +        if (genres.isEmpty()) {
А genres не может null вернуться? Предлагаю использовать для проверки коллекций на наличие в ней элементов CollectionUtils.isEmpty от Apache4 (найдете надеюсь)

2022-10-11 22:12 UTC, mkudryavtsev90 commented on src/main/java/ru/yandex/practicum/filmorate/mapper/FilmRowMapper.java
> +        film.setDuration(Duration.ofMinutes(rs.getInt("film.duration")));
Да, метод rs.getInt("film.duration") != null по контракту. Он возвращает 0 если в соответствующей ячейке БД лежит null

2022-10-11 22:13 UTC, mkudryavtsev90 commented on src/main/java/ru/yandex/practicum/filmorate/mapper/UserRowMapper.java
> +        user.setBirthday(rs.getDate("birthday").toLocalDate());
А здесь действительно может быть null. Добавил проверку

2022-10-12 08:13 UTC, Frilock approved these changes
Принято.

2022-10-12 11:09 UTC, merged